version: '2'

services:
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "8080:15672"

  client:
    build: "./client/"
    links:
      - rabbitmq

  assistant:
    build: "./assistant/"
    links:
      - rabbitmq
