version: '2'

services:
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"

  influxdb:
    image: "influxdb:1.1"
    ports:
      - "8086:8086"

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "8080:15672"

  client:
    build: "./client/"
    restart: on-failure
    links:
      - influxdb
      - rabbitmq

  assistant:
    build: "./assistant/"
    restart: on-failure
    links:
      - influxdb
      - rabbitmq
