version: '2'
services:
#  web:
#    build: .
#    ports:
#     - "5000:5000"
#    volumes:
#     - .:/code
#  redis:
#    image: "redis:alpine"

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "8080:15672"

  client:
    build: "./client/"
    links:
      - rabbitmq

  assistant:
    build: "./assistant/"
    links:
      - rabbitmq